{% set name = "pennylane" %}
{% set version = "0.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane/archive/v{{ version }}.tar.gz
  sha256: 7736a17dc972d918e3a737ce4360d16ac84b9f9f6fca440f167de579c926c114

build:
  entry_points:
    - pl-device-test=pennylane.devices.tests:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - requests
    - appdirs
    - autograd
    - autoray >=0.3.1
    - cachetools
    - networkx
    - numpy <1.24
    - pennylane-lightning >=0.28
    - python >=3.7
    - retworkx
    - scipy
    - semantic_version >=2.7
    - toml

test:
  imports:
    - pennylane
  commands:
    - pip check
    - pl-device-test --help
  requires:
    - pip
    - pytest

about:
  home: https://github.com/PennyLaneAI/pennylane
  summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
  license: Apache-2.0 AND MIT
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
