{% set name = "pennylane" %}
{% set version = "0.33.0" %}
{% set build_num = 2 %}

package:
  name: pennylane-suite
  version: {{ version }}

source:
  - url: https://github.com/PennyLaneAI/pennylane/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b41c843a432c5869fc63dc35c9e9d53bec64d296ca0e0eeb1c9b83d95a68c3f1
    folder: pennylane
  - url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
    sha256: c4cab4a8a1a53edc0990a2a429805dca1c6a46a7ffcc6f77c985b88cd6ff6247
    folder: pennylane-lightning

build:
  number: {{ build_num }}

requirements:
  host:
    - pip
    - python

outputs:
  - name: pennylane-core
    build:
      number: {{ build_num }}
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage('pennylane-core', max_pin='x.x.x') }}
      entry_points:
        - pl-device-test=pennylane.devices.tests:cli
      script: cd "${SRC_DIR}/pennylane" && {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - appdirs
        - autograd
        - autoray >=0.6.1
        - cachetools
        - cvxopt
        - cvxpy
        - networkx
        - numpy
        - opt_einsum
        - python
        - requests
        - rustworkx
        - scipy
        - semantic_version >=2.7
        - toml
        - typing_extensions
      run_constrained:
        - pennylane >=0.30.0
    test:
      imports:
        - pennylane
      requires:
        - setuptools
        - pip

  - name: pennylane-lightning-core
    build:
      number: {{ build_num }}
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage('pennylane-lightning-core', max_pin='x.x.x') }}
      script:
        - cd "${SRC_DIR}/pennylane-lightning"
        - {{ PYTHON }} setup.py build_ext --define="ENABLE_BLAS=ON;ENABLE_OPENMP=ON"  # [not osx or build_platform == target_platform]
        - {{ PYTHON }} setup.py build_ext --define="ENABLE_BLAS=ON;ENABLE_OPENMP=ON;ENABLE_KOKKOS=ON;CMAKE_CXX_COMPILER_TARGET=arm64-apple-macos11;CMAKE_SYSTEM_NAME=Darwin;CMAKE_SYSTEM_PROCESSOR=ARM64"  # [osx and build_platform != target_platform]
        - {{ PYTHON }} setup.py bdist_wheel
        - {{ PYTHON }} -m pip install . --no-deps -vv

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        # Needed for Windows
        - cmake
        - ninja
        - make
      host:
        - libcblas
        - libgomp               # [linux]
        - llvm-openmp >=16.0.3  # [osx]
        - kokkos >=4.0.0,<5
        - kokkos-kernels >=4.0.0,<5
        - pip
        - pybind11
        - python
        - setuptools
        - ninja
      run:
        - ninja
        - numpy
        - python
        - {{ pin_subpackage('pennylane-core') }}
        - {{ pin_compatible('kokkos', min_pin='x.x.x', max_pin='x.x.x') }}
        - {{ pin_compatible('kokkos-kernels', min_pin='x.x.x', max_pin='x.x.x') }}
      run_constrained:
        - pennylane-lightning <0.0a0
    test:
      imports:
        - pennylane_lightning
      requires:
        - setuptools
        - pip

  - name: pennylane
    build:
      number: {{ build_num }}
      skip: true  # [win]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('pennylane-core', max_pin="x.x.x") }}
        - {{ pin_subpackage('pennylane-lightning-core', max_pin="x.x.x") }}
    test:
      imports:
        - pennylane
        - pennylane_lightning
      commands:
        - pypy --version 2> /dev/null || echo Using Python to run tests
        - pypy -c "import pennylane as qml; qml.about()" 2> /dev/null || echo PyPy not found
        - python -c "import pennylane as qml; qml.about()"
        - pip check
        - pl-device-test --help
        - pl-device-test --device default.qubit --shots None --skip-ops
        - pl-device-test --device default.qubit --shots 10000 --skip-ops
        - pl-device-test --device lightning.qubit --shots None --skip-ops
        - pl-device-test --device lightning.qubit --shots 10000 --skip-ops
      requires:
        - setuptools
        - flaky
        - pip
        - pytest
        - pytest-mock

about:
  home: https://github.com/PennyLaneAI/pennylane
  summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
  license: Apache-2.0 AND MIT
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: pennylane/LICENSE
  doc_url: https://pennylane.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - leofang
    - vincentmr
    - BastianZim
  feedstock-name: pennylane
